name: Github Actions dbt Build

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-dbt-models:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: fetch origin
        run:  git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
      - name: Install Python
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.10"
      - name: install requirements
        run: |
          pip install -r requirements.txt
          dbt deps

      - name: run dbt
        id: dbt_build
        shell: bash -l {0}
        run: dbt build
