name: Github Actions CI

on:
  - pull_request

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: fetch origin
        run:  git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
      - name: Install Python
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.10"
      - name: install sqlfluff
        run: "pip install -U pip && pip install sqlfluff sqlfluff-templater-dbt"

      - name: Lint dbt models
        id: sqlfluff_json
        shell: bash -l {0}
        run: git diff --name-only --diff-filter=AMRT HEAD..origin/${{ github.base_ref }} | egrep '\.sql' | { while read -r file; do sqlfluff lint --config ./.sqlfluff --dialect snowflake --templater jinja --ignore templating "$file"; done; }
